USE testdb;
INSERT INTO tb_user (`name`,`age`,`add_time`,`update_time`) VALUES ('张三',18,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('李四',19,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),('王五',20,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO tb_user_level (`user_id`,`cust_level`,`add_time`,`update_time`) VALUES (1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(2,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(3,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO tb_user_hobby (`user_id`,`hobby`,`add_time`,`update_time`) VALUES (1,'打球',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(1,'看书',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(2,'打球',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(2,'看书',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(3,'打球',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),(3,'看书',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
COMMIT;